#import "../../fragments/courseCard.gql"
#import "../../fragments/authorData.gql"

query course ($id: Int!, $totalRecommended: Int = 10) {
  course (id: $id) {
    id
    title
    coverImage
    url
    area
    gallery
    classification {
      title
    }
    dateAndTime{
      text
      startDate
    }
    categories {
      id
      title
    }
    overview
    author {
      ...AuthorData
    }
    instructors {
      id
      profilePicture
      user {
        firstName
        lastName
      }
    }
    location {
      text
      latitude
      longitude
    }
    recommended(totalRecommended: $totalRecommended) {
      ...CourseCard
    }
  }
}