query project ($id: Int!) {
  project (id: $id) {
    id
    title
    coverImage
    category
    author {
      id
      title
      picture
    }
    location
    creationDate
    overview
    positions {
      id
      alreadyApplied
      title
      description
      compensation
      time
      requirements
      randomContributors
    }
  }
}