query course ($id: Int!) {
  course (id: $id) {
    id
    title
    coverImage
    category
    creationDate
    overview
    author {
      title
      profilePicture
    }
    instructors {
      id
      profilePicture
      user {
        firstName
        lastName
      }
    }
    location {
      text
      latitude
      longitude
    }
  }
}