query project ($id: Int!) {
  project (id: $id) {
    id
    title
    coverImage
    category
    location
    creationDate
    overview
    positions {
      title
      description
      compensation
      time
      requirements
    }
    comments {
      owner {
        username
      }
      content
      published
      likes {
        id
      }
    }
  }
}