query project ($id: Int!) {
  project (id: $id) {
    id
    title
    coverImage
    category
    author {
      id
      profilePicture
      user {
        username
        firstName
        lastName
      }
    }
    location
    creationDate
    overview
    positions {
      title
      description
      compensation
      time
      requirements
    }
    comments {
      author {
        username
      }
      content
      published
      likes {
        id
      }
    }
  }
}