query recommendCoursesByCourse ($id: Int!) {
  recommendCoursesByCourse (id: $id) {
    id
    title
    categories {
      id
      title
    }
    coverImage
    author{
      profilePicture
    }
  }
}